# Generated by Django 4.2.1 on 2023-06-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active',
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
