# Generated by Django 4.2.1 on 2023-06-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('TECH', 'TECH'), ('JOBS', 'JOBS'), ('Django', 'Django'), ('React', 'React')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
