# Generated by Django 4.2.1 on 2023-06-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('TECH', 'TECH'), ('JOBS', 'JOBS'), ('Django', 'Django'), ('React', 'React')], default='TECH', max_length=100),
        ),
    ]
